#pragma once
enum OBJ { OBJ_PLAYER, OBJ_MONSTER, OBJ_BULLET, OBJ_BARREL, OBJ_MON_BULLET,OBJ_END };
enum DIR { DIR_LEFT, DIR_RIGHT, DIR_TOP, DIR_BOTTOM, DIR_END };
enum TYPE { NOMAL, BOOM, BOSS, SHILED };
